precision:
    AMP:
        static_loss_scale: 128
        amp: True
    FP32:
        amp: False
    TF32:
        amp: False

platform:
    DGX1V-16G:
        workers: 8
        prefetch: 4
        gpu_affinity: socket_unique_contiguous
    DGX1V-32G:
        workers: 8
        prefetch: 4
        gpu_affinity: socket_unique_contiguous
    T4:
        workers: 8
    DGX1V:
        workers: 8
        prefetch: 4
        gpu_affinity: socket_unique_contiguous
    DGX2V:
        workers: 8
        prefetch: 4
        gpu_affinity: socket_unique_contiguous
    DGXA100:
        workers: 10
        prefetch: 4
        gpu_affinity: socket_unique_contiguous
    OVHA40x1:
        workers: 1
        prefetch: 1
        gpu_affinity: socket_unique_contiguous
    OVHA30x1:
        workers: 1
        prefetch: 1
        gpu_affinity: socket_unique_contiguous
    OVHA100x1:
        workers: 1
        prefetch: 1
        gpu_affinity: socket_unique_contiguous


mode:
    benchmark_training: &benchmark_training
        print_freq: 1
        epochs: 3
        training_only: True
        evaluate: False
        save_checkpoints: False
    benchmark_training_short:
        <<: *benchmark_training
        epochs: 1
        data_backend: syntetic
        prof: 100
    benchmark_inference: &benchmark_inference
        print_freq: 1
        epochs: 1
        training_only: False
        evaluate: True
        save_checkpoints: False
    convergence:
        print_freq: 20
        training_only: False
        evaluate: False
        save_checkpoints: True

anchors:
    # ResNet_like params: {{{
    resnet_params: &resnet_params
        label_smoothing: 0.1
        mixup: 0.2
        lr_schedule: cosine
        momentum: 0.875
        warmup: 8
        epochs: 250
        data_backend: pytorch
        num_classes: 1000
        image_size: 224
        interpolation: bilinear
    # }}}
    # EfficienNet Params: {{{
    efficientnet_params: &efficientnet_params
        optimizer: rmsprop
        rmsprop_alpha: 0.9
        rmsprop_eps: 0.01
        print_freq: 100
        label_smoothing: 0.1
        mixup: 0.2
        lr_schedule: cosine
        momentum: 0.9
        warmup: 16 
        epochs: 400
        data_backend: pytorch
        augmentation: autoaugment
        num_classes: 1000
        interpolation: bicubic
    # }}}
models:
    resnet50: # {{{
    # }}}
    resnext101-32x4d: # {{{
    # }}}
    se-resnext101-32x4d: # {{{
    # }}}
    efficientnet-widese-b0: # {{{
    # }}}
    efficientnet-b0: # {{{
    # }}}
    efficientnet-quant-b0: # {{{
    # }}}
    efficientnet-widese-b4: # {{{
    # }}}
    efficientnet-b4: # {{{
    # }}}
    efficientnet-quant-b4: # {{{
    # }}}
