precision:
    AMP:
        static_loss_scale: 128
        amp: True
    FP32:
        amp: False
    TF32:
        amp: False

platform:
    T4:
        workers: 8
    DGX1V:
        workers: 8
    DGX2V:
        workers: 8
    DGXA100:
        workers: 16

mode:
    benchmark_training: &benchmark_training
        print_freq: 1
        epochs: 3
        training_only: True
        evaluate: False
        save_checkpoints: False
    benchmark_training_short:
        <<: *benchmark_training
        epochs: 1
        data_backend: syntetic
        prof: 100
    benchmark_inference: &benchmark_inference
        print_freq: 1
        epochs: 1
        training_only: False
        evaluate: True
        save_checkpoints: False
    convergence:
        print_freq: 20
        training_only: False
        evaluate: False
        save_checkpoints: True

anchors:
    # ResNet_like params: {{{
    resnet_params: &resnet_params
        model_config: fanin
        label_smoothing: 0.1
        mixup: 0.2
        lr_schedule: cosine
        momentum: 0.875
        warmup: 8
        epochs: 250
        data_backend: pytorch
        num_classes: 1000
        image_size: 224
    resnet_params_896: &resnet_params_896
        <<: *resnet_params
        optimizer_batch_size: 896
        lr: 0.896
        weight_decay: 6.103515625e-05
    resnet_params_1k: &resnet_params_1k
        <<: *resnet_params
        optimizer_batch_size: 1024
        lr: 1.024
        weight_decay: 6.103515625e-05
    resnet_params_2k: &resnet_params_2k
        <<: *resnet_params
        optimizer_batch_size: 2048
        lr: 2.048
        weight_decay: 3.0517578125e-05
    resnet_params_4k: &resnet_params_4k
        <<: *resnet_params
        optimizer_batch_size: 4096
        lr: 4.086
        weight_decay: 3.0517578125e-05
    # }}}

models:
    resnet50: # {{{
        DGX1V:
            AMP:
                <<: *resnet_params_2k
                arch: resnet50
                batch_size: 256
                memory_format: nhwc
            FP32:
                <<: *resnet_params_2k
                batch_size: 112
        DGX2V:
            AMP:
                <<: *resnet_params_4k
                arch: resnet50
                batch_size: 256
                memory_format: nhwc
            FP32:
                <<: *resnet_params_4k
                arch: resnet50
                batch_size: 256
        DGXA100:
            AMP:
                <<: *resnet_params_2k
                arch: resnet50
                batch_size: 256
                memory_format: nhwc
            TF32:
                <<: *resnet_params_2k
                arch: resnet50
                batch_size: 256
        T4:
            AMP:
                <<: *resnet_params_2k
                arch: resnet50
                batch_size: 256
                memory_format: nhwc
            FP32:
                <<: *resnet_params_2k
                batch_size: 128
    # }}}
    resnext101-32x4d: # {{{
        DGX1V:
            AMP:
                <<: *resnet_params_1k
                arch: resnext101-32x4d
                batch_size: 128
                memory_format: nhwc
            FP32:
                <<: *resnet_params_1k
                arch: resnext101-32x4d
                batch_size: 64
        DGXA100:
            AMP:
                <<: *resnet_params_1k
                arch: resnext101-32x4d
                batch_size: 128
                memory_format: nhwc
            TF32:
                <<: *resnet_params_1k
                arch: resnext101-32x4d
                batch_size: 128
        T4:
            AMP:
                <<: *resnet_params_1k
                arch: resnext101-32x4d
                batch_size: 128
                memory_format: nhwc
            FP32:
                <<: *resnet_params_1k
                arch: resnext101-32x4d
                batch_size: 64
    # }}}
    se-resnext101-32x4d: # {{{
        DGX1V:
            AMP:
                <<: *resnet_params_896
                arch: se-resnext101-32x4d
                batch_size: 112
                memory_format: nhwc
            FP32:
                <<: *resnet_params_1k
                arch: se-resnext101-32x4d
                batch_size: 64
        DGXA100:
            AMP:
                <<: *resnet_params_1k
                arch: se-resnext101-32x4d
                batch_size: 128
                memory_format: nhwc
            TF32:
                <<: *resnet_params_1k
                arch: se-resnext101-32x4d
                batch_size: 128
        T4:
            AMP:
                <<: *resnet_params_1k
                arch: se-resnext101-32x4d
                batch_size: 128
                memory_format: nhwc
            FP32:
                <<: *resnet_params_1k
                arch: se-resnext101-32x4d
                batch_size: 64
# }}}
