# SPDX-License-Identifier: Apache-2.0
defaults:
  - hydra/job_logging: primary
  - trainer: ctltrainer
  - evaluator: standard
  - optimizer: Adam
  - criterion: MSE
  - device: cuda
  - callback: standard
  - model: trivial_model
  - dataset: electricity
  - model_dataset: ${defaults.6.model}_${defaults.7.dataset}
    optional: true
  - model_dataset_evaluator: ${defaults.6.model}_${defaults.7.dataset}_${defaults.1.evaluator}
    optional: true
  - model_dataset_device: ${defaults.6.model}_${defaults.7.dataset}_${defaults.4.device}
    optional: true
  - ema: False
    optional: true
  - amp: False
    optional: true

_target_: ???
