# SPDX-License-Identifier: Apache-2.0
# @package _global_
config:
  optimizer:
    _target_: optimizers.optimizer_wrapped
    lr: 1.0
    rho: 0.9
    eps: 1e-06
    weight_decay: 0.0
    name: Adadelta