# SPDX-License-Identifier: Apache-2.0
# @package _global_
config:
  optimizer:
    _target_: optimizers.optimizer_wrapped
    lr: 0.01
    lr_decay: 0.0
    weight_decay: 0.0
    eps: 1e-10
    name: Adagrad
