# SPDX-License-Identifier: Apache-2.0
# @package _global_
config:
  optimizer:
    _target_: optimizers.optimizer_wrapped
    lr: 0.002
    betas: [0.9, 0.999]
    eps: 1e-8
    weight_decay: 0.0
    name: Adamax
