# SPDX-License-Identifier: Apache-2.0
# @package _global_
config:
  optimizer:
    _target_: optimizers.optimizer_wrapped
    lr: 0.01
    lambd: 0.0001
    alpha: 0.75
    t0: 1000000.0
    weight_decay: 0.0
    name: ASGD
