# SPDX-License-Identifier: Apache-2.0
# @package _global_
config:
  optimizer:
    _target_: optimizers.optimizer_wrapped
    lr: 0.01
    momentum: 0.0
    weight_decay: 0.0
    dampening: 0.0
    nesterov: False
    name: SGD

