# SPDX-License-Identifier: Apache-2.0
# @package _global_
config:
  evaluator:
    checkpoint: ???
  inference:
    _target_: inference.inference.run_inference
    batch_size: 64
    precision: fp32

