# SPDX-License-Identifier: Apache-2.0
# @package _global_
config:
  model:
    _target_: models.lstm.LSTM
    hidden_size: 160
    dropout: 0.1
    missing_data_strategy: 'mask'
  trainer:
    batch_size: 2048
    num_epochs: 10
  optimizer:
    lr: .004
