# SPDX-License-Identifier: Apache-2.0
# @package _global_
config:
  model:
    _target_: models.tft_pyt.modeling.TemporalFusionTransformer
    quantiles: [ .5 ]
    n_head: 4
    hidden_size: 160
    dropout: 0.1
    attn_dropout: 0
