# SPDX-License-Identifier: Apache-2.0
config:
  model:
    quantiles: [.1 ,.5 , .9]
    n_head: 4
    hidden_size: 128
    dropout: 0.3
    attn_dropout: 0
  trainer:
    batch_size: 1024
    num_epochs: 10
  optimizer:
    lr: .001
    gradient_norm: 1.0
  evaluator:
    metrics: [P50, P90, MSE, MAE]

