# SPDX-License-Identifier: Apache-2.0
# @package _global_
config:
  evaluator:
    _target_: evaluators.evaluation_metrics.MetricEvaluator
    output_selector: -1
    label_selector: -1
    metrics:
      - MSE
      - MAE
      - RMSE
      - SMAPE
    precision: 5
    use_weights: False
