# SPDX-License-Identifier: Apache-2.0
# @package _global_
config:
  trainer:
    callback:
      early_stopping:
        _target_: callbacks.ctl_callbacks.EarlyStopping
        metric: val_loss
        max_diff: 0
        patience: 5
      save_best_checkpoint:
        _target_: callbacks.ctl_callbacks.SaveBestCheckpoint
        metric: val_loss
      throughput_benchmark:
        _target_: callbacks.ctl_callbacks.ThroughputBenchmark
        warmup_epochs: 0
      logging:
        _target_: callbacks.ctl_callbacks.LoggingCallback
               
