# SPDX-License-Identifier: Apache-2.0
# @package _global_
config:
  dataset:
    _target_: data.data_utils.create_datasets
    source_path: /workspace/datasets/traffic/traffic.csv
    dest_path: /workspace/datasets/traffic/
    time_ids: 'sensor_day'
    train_range:
      - 0
      - 151
    valid_range:
      - 144
      - 166
    test_range:
      - 159
      - 2000
    dataset_stride: 1
    scale_per_id: False
    encoder_length: 168
    example_length: 192
    features:
      - name: 'id'
        feature_type: 'ID'
        feature_embed_type: 'CATEGORICAL'
        cardinality: 964
      - name: 'hours_from_start'
        feature_type: 'TIME'
        feature_embed_type: 'CONTINUOUS'
      - name: 'values'
        feature_type: 'TARGET'
        feature_embed_type: 'CONTINUOUS'
        scaler:
                _target_: sklearn.preprocessing.StandardScaler
      - name: 'time_on_day'
        feature_type: 'KNOWN'
        feature_embed_type: 'CONTINUOUS'
        scaler:
                target: sklearn.preprocessing.StandardScaler
      - name: 'day_of_week'
        feature_type: 'KNOWN'
        feature_embed_type: 'CATEGORICAL'
        cardinality: 8
      - name: 'hours_from_start'
        feature_type: 'KNOWN'
        feature_embed_type: 'CONTINUOUS'
        scaler:
                target: sklearn.preprocessing.StandardScaler
      - name: 'categorical_id'
        feature_type: 'STATIC'
        feature_embed_type: 'CATEGORICAL'
        cardinality: 964
    train_samples: 450000
    valid_samples: 50000
    binarized: True
    time_series_count: 964
